### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by amirziai** [sixch/combine_data_wrangling#1]
@sixch can you please move the content of the `NFLcombineDataWrangling.docx` file to  `README.md`? That way it's visible on GitHub and you don't need to download the Word doc to see it.

**Comment by sixch** [comment]
Oh ok. Was going to ask you that tonight. Wasn’t sure how Springboard
wanted me to submit a paper.

**Comment by sixch** [comment]
Project description is now in the README.md
