### ISSUE TITLE
Percentage calculation

### ISSUE THREAD

**Issue by amirziai** [sixch/combine_data_wrangling#3]
@sixch think about how you can do your percentage calculations programmatically vs. looking up the values and passing them to `percentage(part, whole)`. 

For example looking at `In [776]` when you run:
```
hand = nfla["hands"].value_counts().nlargest()
```
you get back a series. Series have indices and values. You can grab the value for a given index using:
```
value_for_0 = hand.iloc[0]
```

Once you have the value you can divide by the total to get the percentage:
```
value_for_0 / float(len(nfla))  # or just value_for_0 / len(nfla) if you're using Python 3
```

**Comment by sixch** [comment]
@amirziai  thanks for the tips. I changed my percentage calculations. Here's an example of what I did:


`# Percentage of amount of rows are 0.0 in hands column`
`hand_0 = hand.iloc[0]`
`hand_perc= round(hand_0 / float(len(nfla))*100,2)`
`print "Percentage of column hands with missing values: ",hand_perc,'%'`

Which produced this ouput:
Percentage of column hands with missing values:  76.49 %
