### ISSUE TITLE
inplace=True

### ISSUE THREAD

**Issue by amirziai** [sixch/combine_data_wrangling#5]
I'm not a big fan of using `inplace=True`, mostly because it makes your code harder to reason about. This is probably not very important at this point but just in case you'd like to know more:
https://stackoverflow.com/questions/22532302/pandas-peculiar-performance-drop-for-inplace-rename-after-dropna

**Comment by sixch** [comment]
@amirziai thanks. Sounds like the inplace=True is slow, I changed my code from:

`nfld['position'].replace({'OC': 'C'}, inplace=True)`

to:

`nfld.replace(['OC'], ['C'])`
